buildscript {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url = 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath "net.neoforged:moddev-gradle:2.0.144"
    }
}

apply plugin: 'net.neoforged.moddev'
apply plugin: 'maven-publish'

version = project.mod_version
group = project.maven_group

repositories {
    mavenCentral()
    maven { url = 'https://maven.neoforged.net/releases' }
}

dependencies {
    implementation "org.apache.commons:commons-math3:3.6.1"
    compileOnly 'com.google.code.findbugs:jsr305:3.0.2'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-Xlint:unchecked' << '-Xlint:deprecation'
    it.options.release = 21
}

neoForge {
    version = project.neoforge_version
    
    runs {
        client {
            type = 'client'
        }
        server {
            type = 'server'
        }
    }
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
    manifest {
        attributes(
            'Mod-Loader': 'neoforge',
            'Loader-Version': project.neoforge_version,
            'Mod-Id': 'superfastmath',
            'Mod-Version': project.version,
            'Mod-Name': 'SuperFastMath',
            'Mixin-Configs': 'superfastmath.mixins.json'
        )
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('processResources') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from('src/main/resources') {
        include 'superfastmath.mixins.json'
        expand('version': project.version)
    }
    from('src/main/resources/META-INF') {
        include 'mods.toml'
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }
    repositories {
        maven {
            url = uri(layout.buildDirectory.dir("repo"))
        }
    }
}