# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G -Dneoforge.disableAccessTransformers=true
org.gradle.parallel=true
org.gradle.configuration-cache=false

# NeoForge Properties
minecraft_version=1.21.1
neoforge_version=21.1.70

# Mod Properties
mod_version=0.0.5-1.21.1
maven_group=org.elias.fastmath
archives_base_name=superfastmath